### ISSUE TITLE
bounding box just label one person?

### ISSUE THREAD

**Issue by strugglingyq** [qiaoguan/Fall-detection#1]

**Comment by qiaoguan** [comment]
You can alter the source code in gq.py,  we hold the view that for fall detection problem, we only need to detect one person(the reason is that if there are more person,  there is no need the detection if a person has called, fall detection may be used for helping old person, ie, if a lonely old person fall down , his or her child can know with the help of fall detection).  The detection model are based on darknet and  is trained on voc(voc dataset has 20class,  including person). We only need the person class,  however, for the inside fall detection, if there is only person(no dog) , if we detect a dog, we  can think  there is a person fall down,  cause the falling down person really like a dog.  Hope it works for you
